name: Compiler workflow for alpine
on:
  workflow_dispatch:
    inputs:
      redisv:
        description: 'redis version'
        default: '7.2.11'
        required: false
        type: string
      osv:
        description: 'alpine version'
        default: '3.23.0'
        required: false
        type: string

jobs:
  compile:
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
        # platform: ["amd64"]
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Prepare redis src
      run: |
        wget https://download.redis.io/releases/redis-${{ inputs.redisv }}.tar.gz
        tar -xzf redis-${{ inputs.redisv }}.tar.gz
        ls -lh redis-${{ inputs.redisv }}
      working-directory: /tmp
    - name: compile redis for system page size = 12
      run: |
        docker run --platform linux/${{ matrix.platform }} --rm -v /tmp/redis-${{ inputs.redisv }}:/workspace -w /workspace djangoyi/redis-compiler:alpine-${{ inputs.osv }} sh -c "JEMALLOC_CONFIGURE_OPTS='--with-lg-page=12' make BUILD_TLS=yes && make PREFIX=/workspace/12 install && strip /workspace/12/bin/*"
    - name: compile redis for system page size = 16
      run: |
        docker run --platform linux/${{ matrix.platform }} --rm -v /tmp/redis-${{ inputs.redisv }}:/workspace -w /workspace djangoyi/redis-compiler:alpine-${{ inputs.osv }} sh -c "JEMALLOC_CONFIGURE_OPTS='--with-lg-page=16' make BUILD_TLS=yes && make PREFIX=/workspace/16 install && strip /workspace/16/bin/*"
    - name: pack bin files
      run: |
        tar -czf /tmp/redis-${{ inputs.redisv }}-${{ matrix.platform }}.tgz 12 16
      working-directory: /tmp/redis-${{ inputs.redisv }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: alpine-${{ matrix.platform }}
        path: /tmp/redis-${{ inputs.redisv }}-${{ matrix.platform }}.tgz

  release:
    runs-on: ubuntu-latest
    needs: compile
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: Remove release
    #   uses: liudonghua123/delete-release-action@v1
    #   with:
    #     release_name: redis-${{ inputs.redisv }}_ubuntu-${{ inputs.osv }}
    #     suppress_errors: true
    # - name: Remove tag
    #   run: |
    #     git tag -d mongo-${{ needs.export.outputs.mongo }}_ubuntu-${{ needs.export.outputs.ubuntu }} || :
    #     git push origin --delete mongo-${{ needs.export.outputs.mongo }}_ubuntu-${{ needs.export.outputs.ubuntu }} || :
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        pattern: alpine-*
        path: release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/alpine-*/*
        tag_name: redis-${{ inputs.redisv }}_alpine-${{ inputs.osv }}
